[BD-26][EDUCATOR-5811] Add missed proctored exam instruction pages
edx/frontend-lib-special-exams pull request #18
Opened 2021-06-04 12:11 UTC by UvgenGen

**Description**: Add missed proctored exam instruction pages.

**Jira**: https://openedx.atlassian.net/browse/EDUCATOR-5811

2021-06-04 12:12 UTC, edx-webhook commented
Thanks for the pull request, @UvgenGen! I've created [BLENDED-874](https://openedx.atlassian.net/browse/BLENDED-874) to keep track of it in Jira.   More details are on the [BD-26](https://openedx.atlassian.net/wiki/spaces/COMM/pages/2523627980/BD-26+Proctoring+MFE+and+configuration) project page.


When this pull request is ready, tag your edX technical lead.


<!-- comment:welcome-blended -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2021-06-07 14:16 UTC, Zacharis278 requested changes

2021-06-07 14:16 UTC, Zacharis278 commented on src/instructions/Instructions.test.jsx
> +  it('Instructions for error status', () => {
left a comment about this test in another PR, we should make sure to test the escalation/contact link as well. We can merge this for now and cover it in that test PR just to keep things moving.

2021-06-07 14:16 UTC, Zacharis278 commented on src/instructions/proctored_exam/EntranceProctoredExamInstructions.jsx
> +                defaultMessage="You will have 25 minutes to complete your exam."
it looks like we just missed a hard coded number here, this value should be the time remaining for the attempt

2021-06-07 14:16 UTC, Zacharis278 commented on src/instructions/Instructions.test.jsx
> +    expect(screen.getByText('Your exam is ready to be resumed.')).toBeInTheDocument();
I think we should be testing for the correct "remaining time" value here. If you want to cover this in one of the test PRs that's fine by me

2021-06-07 14:16 UTC, Zacharis278 commented on src/instructions/proctored_exam/ErrorProctoredExamInstructions.jsx
> +          <Hyperlink href={contactUsUrl}>
there should be two different cases for the contact link here depending on if there is a "proctoring_escalation_email" setup for the course team or not

2021-06-08 12:58 UTC, ViktorRusakov commented
@Zacharis278 I fixed the issues with hardcoded values, we will also have a PR in edx-proctoring for this since currently both remaining time and proctoring_escalation_email are not included in any of our APIs
we will fix tests in another PR

2021-06-08 13:27 UTC, Zacharis278 approved these changes

2021-06-08 13:27 UTC, merged